apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoserver
  namespace: ns-sigemad-release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
  template:
    metadata:
      labels:
        app: geoserver
    spec:
      containers:
        - name: geoserver
          image: kartoza/geoserver:2.25.2
          ports:
            - containerPort: 8080
          env:
            - name: GEOSERVER_ADMIN_USER
              value: admin
            - name: GEOSERVER_ADMIN_PASSWORD
              value: GEOtest1
            - name: SAMPLE_DATA
              value: "true" # Habilita los datos de prueba
          volumeMounts:
            - name: geoserver-data
              mountPath: /var/local/geoserver
      volumes:
        - name: geoserver-data
          persistentVolumeClaim:
            claimName: pvc-geoserver
