apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sqlserver
  namespace: ns-sigemad-release
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
