apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: ns-sigemad
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31433  # Puedes elegir un puerto entre 30000 y 32767
  type: NodePort
